env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - standard
  - eslint-config-prettier
globals:
  test: writable
  expect: writable
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    version: detect
